# Tarea 8
**Programación I**  
## Elmer Humberto Lémus Flores

In [1]:
import numpy as np

## Ejercicio 1

Cree una matriz que contenga ceros. Rellene la mitad de ellos aleatoriamente con unos.

In [2]:
# Ingreso de dimensiones de la matriz

filas = int(input("Filas: "))
columnas = int(input("Columnas: "))

# Creación de lista de ceros
a = np.zeros(filas*columnas)

# Creación de indice de coordenadas
b = np.arange(filas*columnas)

# Creación de coordenadas
c = np.random.choice(b,int(filas*columnas/2),replace=False)

# Reemplazo por 1
a[c]=1

# Transformación a matriz
a.resize(filas,columnas)
print("\n",a)
print("\n","Total de puntos aleatorios: ", a.sum())

Filas: 5
Columnas: 5

 [[0. 0. 0. 1. 0.]
 [1. 1. 0. 1. 0.]
 [0. 1. 0. 0. 1.]
 [0. 0. 1. 0. 1.]
 [1. 1. 0. 1. 1.]]

 Total de puntos aleatorios:  12.0


In [3]:
# Para crear una matriz sin restricción de unos

a = np.random.randint(0,2,[filas, columnas])
print(a)
a.sum()

[[1 1 0 0 0]
 [1 0 1 0 0]
 [0 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 1 0]]


9

## Ejercicio 2
Cree dos matrices de dimensiones $(5,2)$. La primera rellena de ceros y la siguiente de unos. 

In [4]:
# Se solicitan las dimensiones de la matriz
f = 5
c = 2

# Creamos la matriz de ceros
zero = np.zeros([f, c])
one = np.ones([f, c])

# Impresión de tableros
print(zero, "\n")
print(one)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]] 

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


1.	Convierta las matrices en vectores columna.

In [5]:
# Se modifica la forma de la matriz con resize, la cual sí afecta la forma de la matriz original
zero.resize(f*c, 1)
zero

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [6]:
# Se modifica la forma de la matriz con resize, la cual sí afecta la forma de la matriz original
one.resize(f*c, 1)
one

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

2.	Apile ambos vectores a lo largo de una tercera dimensión.

In [7]:
# Se concantenan los valores verticalmente
tercera = np.dstack((zero,one))
tercera

array([[[0., 1.]],

       [[0., 1.]],

       [[0., 1.]],

       [[0., 1.]],

       [[0., 1.]],

       [[0., 1.]],

       [[0., 1.]],

       [[0., 1.]],

       [[0., 1.]],

       [[0., 1.]]])

3.	Con las matrices originales, conviértalas en vectores fila y concaténelos verticalmente.

In [8]:
# Se pasan las matrices a filas
zero.reshape(1,f*c)
one.reshape(1,f*c)

# se concantenan verticalmente
np.vstack((zero,one))

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

## Ejercicio 3

Dada la función $f(x,y,z) = 2x +3y + z^2$

In [9]:
# Se define la función
def f(x,y,z):
    return (2*x) + (3*y) + (z**2)

1.	Genere una matriz con números aleatorios para cada variable.

In [10]:
# Cantidad de valores para cada variable
fila = int(input("Filas: "))

Filas: 10


In [11]:
# Llenamos los valores de x, y, z con valores aleatorios
x = np.random.randint(0,100,[fila, 1])
y = np.random.randint(0,100,[fila, 1])
z = np.random.randint(0,100,[fila, 1])

# Creamos una matriz con los valores de las variables anteriores
matrix = np.hstack((x,y,z))
matrix

array([[34, 59,  3],
       [90, 54, 68],
       [55, 63, 31],
       [64, 53, 15],
       [55, 73, 38],
       [89, 92, 99],
       [25, 44, 54],
       [94, 87, 14],
       [85, 41,  5],
       [80, 88, 21]])

2.	Evalúe la matriz anterior en la función. El resultado debe ser un vector columna.

In [12]:
# Evaluamos los valores en la función
f(x,y,z)

array([[  254],
       [ 4966],
       [ 1260],
       [  512],
       [ 1773],
       [10255],
       [ 3098],
       [  645],
       [  318],
       [  865]])

## Ejercicio 4

Suponga que dentro de un cuadrado de lado 50 cm, hay un cuadrado de 20cm. Ambos cuadrados comparten centro. Estime el área del cuadrado interno por método Monte Carlo. [Consulte Aquí]( http://mathonweb.com/entrtain/monte/t_monte.htm)

In [13]:
# Se crea la matriz de 50 por 50
f = 50
c = 50

# Creamos la matriz de ceros
area_total = np.random.randint(0,2,[f, c])

# Impresión de tablero
print("Matriz de área total")
print(area_total,"\n")

# Área total del tablero máx = 50*50 (2,500)
area_total.sum()
print("El área total es: ", area_total.sum(), "\n")

# Extracción del área pequeña
print("Matriz de área parcial")
area_parcial = area_total[15:35,15:35]

# Impresión del área parcial, cuadrado de 20*20
print(area_parcial)

# área máxima = 20*20 (400)
area_parcial.sum()
print("El área parcial es: ",area_parcial.sum())

# Proporción de áreas
esti = area_parcial.sum()/area_total.sum()*100
esti
print("La proporción del área es: ",esti)

Matriz de área total
[[1 1 1 ... 0 0 1]
 [1 0 1 ... 0 0 1]
 [0 1 1 ... 1 0 0]
 ...
 [0 1 1 ... 1 0 0]
 [1 0 1 ... 1 1 1]
 [0 0 1 ... 0 1 1]] 

El área total es:  1252 

Matriz de área parcial
[[1 0 0 0 0 0 0 0 0 1 1 0 1 1 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0 1 0 0 0 0 1 1 1 1 1 1 1]
 [0 0 1 1 1 1 0 1 0 0 1 0 0 1 0 1 0 0 1 1]
 [0 1 0 1 1 0 1 1 0 0 0 1 0 0 0 0 1 0 0 0]
 [1 1 0 1 1 0 0 1 0 1 0 0 1 0 1 0 0 0 0 0]
 [0 1 1 1 1 1 1 0 1 1 0 1 1 0 1 0 0 0 0 0]
 [0 0 1 0 0 1 0 0 1 1 0 1 1 1 0 0 0 1 1 0]
 [0 1 1 1 0 0 1 0 0 1 1 1 0 0 1 1 1 1 0 0]
 [1 1 1 1 0 0 0 0 1 1 0 0 1 0 0 1 0 1 1 1]
 [0 0 0 0 1 0 0 1 1 0 0 1 0 1 1 0 1 1 0 0]
 [0 0 0 1 0 1 1 0 1 1 1 0 1 0 0 1 1 0 0 1]
 [1 1 0 1 1 0 1 1 0 1 1 1 1 1 0 1 1 1 0 1]
 [0 1 0 0 1 0 1 1 1 0 0 0 0 1 1 1 0 1 1 0]
 [0 1 0 0 1 1 1 1 1 0 1 0 0 0 0 1 0 1 0 1]
 [1 0 0 0 0 1 0 1 1 1 0 0 0 1 0 0 0 1 1 0]
 [0 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 0 0 0 1]
 [1 0 0 1 0 1 1 0 1 0 1 0 0 0 0 0 0 0 1 0]
 [1 1 0 1 1 1 1 1 1 1 0 0 0 0 0 0 0 1 1 1]
 [0 1 0 1 0 0 0 1 1 0 1 1 0 0 0 1 

In [14]:
# El área total del cuadrado será
area_final = esti/100*2500
print("La estimación del área del cuadrado de 20*20 es ",area_final, "cm cuadrados")

La estimación del área del cuadrado de 20*20 es  379.39297124600637 cm cuadrados


## Ejercicio 5

### *Tarea*

1. De las siguientes secciones, escoger 73 funciones de NumPy y mostrar su utilización en un ejemplo.

    - [Array creation routines](https://numpy.org/devdocs/reference/routines.array-creation.html)

    - [Array manipulation routines](https://numpy.org/devdocs/reference/routines.array-manipulation.html)

    - [Binary operations](https://numpy.org/devdocs/reference/routines.bitwise.html)

    - [String operations](https://numpy.org/devdocs/reference/routines.char.html)

### Array creation routines

#### Ones and zeros

In [15]:
# 1
# numpy.empty
# numpy.empty(shape, dtype=float, order='C')
# Return a new array of given shape and type, without initializing entries.

a = np.empty([5,5], dtype=int, order='C')
a

array([[1038391352,        564,         50,          0,          0],
       [         0,          0,          0,          0,    3145808],
       [1852990827,  892234853,  842545251,  758263862,  892744291],
       [1647916077, 1633758565, 1663907383, 1664299831, 1647458659],
       [ 775436131, 1952543859,    7631733, 1701183488,  842621493]])

In [16]:
# 2
# numpy.eye
# numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C')
# Return a 2-D array with ones on the diagonal and zeros elsewhere.

a = np.eye(5, dtype=int)
a

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [17]:
# 3
# numpy.identity
# numpy.identity(n, dtype=None)
# Return the identity array. The identity array is a square array with 
# ones on the main diagonal.


a = np.identity(5, dtype=int)
a

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [18]:
# 4
# numpy.ones
# numpy.ones(shape, dtype=None, order='C')
# Return a new array of given shape and type, filled with ones.

a = np.ones((5,5), dtype=int)
a

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [19]:
# 5
# numpy.zeros
# numpy.zeros(shape, dtype=float, order='C')
# Return a new array of given shape and type, filled with zeros.

a = np.zeros((5,5), dtype=int)
a

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [20]:
# 6
# numpy.full
# numpy.full(shape, fill_value, dtype=None, order='C')
# Return a new array of given shape and type, filled with fill_value.

a = np.full((5, 5), 10)
a

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

#### From existing data

In [21]:
# 7
# numpy.array
# numpy.array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
# Create an array.

a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [22]:
# 8
# numpy.asarray
# numpy.asarray(a, dtype=None, order=None)
# Convert the input to an array.

a = [1, 2, 3]
np.asarray(a)

array([1, 2, 3])

In [23]:
# 9
# numpy.asanyarray
# numpy.asanyarray(a, dtype=None, order=None)
# Convert the input to an ndarray, but pass ndarray subclasses through.

a = [1, 2]
np.asanyarray(a)

array([1, 2])

In [24]:
# 10
# numpy.ascontiguousarray
# numpy.ascontiguousarray(a, dtype=None)
# Return a contiguous array (ndim >= 1) in memory (C order).

a = np.arange(6).reshape(2,3)
np.ascontiguousarray(a, dtype=np.float32)

array([[0., 1., 2.],
       [3., 4., 5.]], dtype=float32)

In [25]:
# 11
# numpy.asmatrix
# numpy.asmatrix(data, dtype=None)
# Interpret the input as a matrix.
# Unlike matrix, asmatrix does not make a copy if the input is already a matrix 
# or an ndarray. Equivalent to matrix(data, copy=False).

x = np.array([[1, 2], [3, 4]])
m = np.asmatrix(x)
m

matrix([[1, 2],
        [3, 4]])

In [26]:
# 12
# numpy.copy
# numpy.copy(a, order='K')
# Return an array copy of the given object.

np.array(a, copy=True) 

array([[0, 1, 2],
       [3, 4, 5]])

In [27]:
x = np.array([1, 2, 3])
y = x
print(y)
z = np.copy(x)
print(x)

[1 2 3]
[1 2 3]


In [28]:
# 13
# numpy.frombuffer
# numpy.frombuffer(buffer, dtype=float, count=-1, offset=0)
# Interpret a buffer as a 1-dimensional array.

s = b'hello world'
np.frombuffer(s, dtype='S1', count=11, offset=0)

array([b'h', b'e', b'l', b'l', b'o', b' ', b'w', b'o', b'r', b'l', b'd'],
      dtype='|S1')

In [29]:
# 14
# numpy.fromfunction
# numpy.fromfunction(function, shape, *, dtype=<class 'float'>, **kwargs)
# Construct an array by executing a function over each coordinate.
# The resulting array therefore has a value fn(x, y, z) at coordinate (x, y, z).

np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [30]:
np.fromfunction(lambda i, j: i + j, (8, 8), dtype=int)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 2,  3,  4,  5,  6,  7,  8,  9],
       [ 3,  4,  5,  6,  7,  8,  9, 10],
       [ 4,  5,  6,  7,  8,  9, 10, 11],
       [ 5,  6,  7,  8,  9, 10, 11, 12],
       [ 6,  7,  8,  9, 10, 11, 12, 13],
       [ 7,  8,  9, 10, 11, 12, 13, 14]])

In [31]:
# 15
# numpy.fromiter
# numpy.fromiter(iterable, dtype, count=-1)
# Create a new 1-dimensional array from an iterable object.

iterable = (x*x for x in range(5))
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [32]:
# 16
# numpy.fromstring
# numpy.fromstring(string, dtype=float, count=-1, sep='')
# A new 1-D array initialized from text data in a string.

np.fromstring('1 2', dtype=int, sep=' ')

array([1, 2])

#### Numerical ranges

In [33]:
# 17
# numpy.arange
# numpy.arange([start, ]stop, [step, ]dtype=None)
# Return evenly spaced values within a given interval.

np.arange(1,15,2)

array([ 1,  3,  5,  7,  9, 11, 13])

In [34]:
# 18
# numpy.linspace
# numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
# Return evenly spaced numbers over a specified interval.

np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [35]:
np.linspace(2.0, 3.0, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [36]:
np.linspace(2.0, 3.0, num=5, retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

In [37]:
# 19
# numpy.logspace
# numpy.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None, axis=0)
# Return numbers spaced evenly on a log scale.

np.logspace(0.0, 3.0, num=10, endpoint=True, base=10.0)

array([   1.        ,    2.15443469,    4.64158883,   10.        ,
         21.5443469 ,   46.41588834,  100.        ,  215.443469  ,
        464.15888336, 1000.        ])

In [38]:
# 20
# numpy.geomspace
# numpy.geomspace(start, stop, num=50, endpoint=True, dtype=None, axis=0)
# Return numbers spaced evenly on a log scale (a geometric progression).

np.geomspace(1, 1000, num=3, endpoint=False)

array([  1.,  10., 100.])

In [39]:
# 21
# numpy.meshgrid
# numpy.meshgrid(*xi, copy=True, sparse=False, indexing='xy')
# Return coordinate matrices from coordinate vectors.

nx, ny = (3, 2)
x = np.linspace(0, 1, nx)
y = np.linspace(0, 1, ny)
xv, yv = np.meshgrid(x, y)
print(xv)
print(yv)

[[0.  0.5 1. ]
 [0.  0.5 1. ]]
[[0. 0. 0.]
 [1. 1. 1.]]


In [40]:
# 22
# numpy.mgrid
# numpy.mgrid = <numpy.lib.index_tricks.MGridClass object>
# nd_grid instance which returns a dense multi-dimensional “meshgrid”.

np.mgrid[0:5,0:5]

array([[[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])

In [41]:
# 23
# numpy.ogrid
# numpy.ogrid = <numpy.lib.index_tricks.OGridClass object>
# nd_grid instance which returns an open multi-dimensional “meshgrid”.

from numpy import ogrid
ogrid[0:5,0:5]

[array([[0],
        [1],
        [2],
        [3],
        [4]]), array([[0, 1, 2, 3, 4]])]

#### Building matrices

In [42]:
# 24
# numpy.diag
# numpy.diag(v, k=0)
# Extract a diagonal or construct a diagonal array.

x = np.arange(9).reshape((3,3))
print(x)
np.diag(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([0, 4, 8])

In [43]:
np.diag(x, k=1)

array([1, 5])

In [44]:
np.diag(x, k=-1)

array([3, 7])

In [45]:
np.diag(np.diag(x))

array([[0, 0, 0],
       [0, 4, 0],
       [0, 0, 8]])

In [46]:
# 25
# numpy.diagflat
# numpy.diagflat(v, k=0)
# Create a two-dimensional array with the flattened input as a diagonal.

np.diagflat([[1,2], [3,4]], k=0)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [47]:
# 26
# numpy.tri
# numpy.tri(N, M=None, k=0, dtype=<class 'float'>)
# An array with ones at and below the given diagonal and zeros elsewhere.

np.tri(5, 5, 0, dtype=int)

array([[1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1]])

In [48]:
# 27
# numpy.tril
# numpy.tril(m, k=0)
# Lower triangle of an array.

np.tril([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], -1)

array([[ 0,  0,  0],
       [ 4,  0,  0],
       [ 7,  8,  0],
       [10, 11, 12]])

In [49]:
# 28
# numpy.triu
# numpy.triu(m, k=0)
# Upper triangle of an array.

np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], -1)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])

In [50]:
# 29
# numpy.vander
# numpy.vander(x, N=None, increasing=False)
# Generate a Vandermonde matrix.

x = np.array([1, 2, 3, 5])
np.vander(x)

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [125,  25,   5,   1]])

In [51]:
np.vander(x, increasing=True)

array([[  1,   1,   1,   1],
       [  1,   2,   4,   8],
       [  1,   3,   9,  27],
       [  1,   5,  25, 125]])

#### The Matrix class

In [52]:
# 30
# numpy.mat
# numpy.mat(data, dtype=None)
# Interpret the input as a matrix.

x = np.array([[1, 2], [3, 4]])
m = np.asmatrix(x)
print(m)

[[1 2]
 [3 4]]


In [53]:
# 31
# numpy.bmat
# numpy.bmat(obj, ldict=None, gdict=None)
# Build a matrix object from a string, nested sequence, or array.

A = np.mat('1 1; 1 1')
B = np.mat('2 2; 2 2')
C = np.mat('3 4; 5 6')
D = np.mat('7 8; 9 0')

np.bmat([[A, B], [C, D]])

matrix([[1, 1, 2, 2],
        [1, 1, 2, 2],
        [3, 4, 7, 8],
        [5, 6, 9, 0]])

In [54]:
np.bmat(np.r_[np.c_[A, B], np.c_[C, D]])

matrix([[1, 1, 2, 2],
        [1, 1, 2, 2],
        [3, 4, 7, 8],
        [5, 6, 9, 0]])

In [55]:
np.bmat('A,B; C,D')

matrix([[1, 1, 2, 2],
        [1, 1, 2, 2],
        [3, 4, 7, 8],
        [5, 6, 9, 0]])

## Array manipulation routines

#### Basic operations

In [56]:
# 32
# numpy.copyto
# numpy.copyto(dst, src, casting='same_kind', where=True)
# Copies values from one array to another, broadcasting as necessary.

a = np.array([1,2,3])
b = np.array([4,5,6])
np.copyto(b,a)
b

array([1, 2, 3])

In [57]:
# 33
# numpy.shape
# numpy.shape(a)
# Return the shape of an array.

np.shape(np.eye(3))

(3, 3)

#### Changing array shape

In [58]:
# 34
# numpy.reshape
# numpy.reshape(a, newshape, order='C')
# Gives a new shape to an array without changing its data.

a = np.array([[1,2,3], [4,5,6]])
print(a)
np.reshape(a, 6)

[[1 2 3]
 [4 5 6]]


array([1, 2, 3, 4, 5, 6])

In [59]:
# 35
# numpy.ravel
# numpy.ravel(a, order='C')
# Return a contiguous flattened array.

x = np.array([[1, 2, 3], [4, 5, 6]])
np.ravel(x)

array([1, 2, 3, 4, 5, 6])

In [60]:
# 36
# numpy.ndarray.flat
# ndarray.flat
# Return a contiguous flattened array.

x = np.arange(1, 7).reshape(2, 3)
print(x)
x.flat[3]

[[1 2 3]
 [4 5 6]]


4

In [61]:
print(x.T)
x.T.flat[3]

[[1 4]
 [2 5]
 [3 6]]


5

In [62]:
# 37
# numpy.ndarray.flatten
# ndarray.flatten(order='C')
# order:{‘C’, ‘F’, ‘A’, ‘K’}, optional

a = np.array([[1,2], [3,4]])
a.flatten()

array([1, 2, 3, 4])

In [63]:
a.flatten('F')

array([1, 3, 2, 4])

#### Transpose-like operations

In [64]:
# 38
# numpy.moveaxis
# numpy.moveaxis(a, source, destination)
# Move axes of an array to new positions.

x = np.zeros((3, 4, 5))
np.moveaxis(x, 0, -1).shape

(4, 5, 3)

In [65]:
np.moveaxis(x, -1, 0).shape

(5, 3, 4)

In [66]:
# 39
# numpy.rollaxis
# numpy.rollaxis(a, axis, start=0)
# Roll the specified axis backwards, until it lies in a given position.

a = np.ones((3,4,5,6))
np.rollaxis(a, 3, 1).shape

(3, 6, 4, 5)

In [67]:
np.rollaxis(a, 2).shape

(5, 3, 4, 6)

In [68]:
np.rollaxis(a, 1, 4).shape

(3, 5, 6, 4)

In [69]:
# 40
# numpy.swapaxes
# numpy.swapaxes(a, axis1, axis2)
# Interchange two axes of an array.

x = np.array([[1,2,3]])
np.swapaxes(x,0,1)

array([[1],
       [2],
       [3]])

In [70]:
# 41
# numpy.ndarray.T
# ndarray.T
# The transposed array.

x = np.array([[1.,2.],[3.,4.]])
print(x)
print(x.T)

[[1. 2.]
 [3. 4.]]
[[1. 3.]
 [2. 4.]]


In [71]:
# 42
# numpy.transpose
# numpy.transpose(a, axes=None)
# Reverse or permute the axes of an array; returns the modified array.

x = np.arange(4).reshape((2,2))
print(x)
np.transpose(x)

[[0 1]
 [2 3]]


array([[0, 2],
       [1, 3]])

#### Changing number of dimensions

In [72]:
# 43
# numpy.atleast_1d
# numpy.atleast_1d(*arys)
# Convert inputs to arrays with at least one dimension.

x = np.arange(9.0).reshape(3,3)
np.atleast_1d(x)

# tambien se usa para 2d y 3d

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [73]:
# 44
# numpy.broadcast
# class numpy.broadcast
# Produce an object that mimics broadcasting.

x = np.array([[1], [2], [3]])
y = np.array([4, 5, 6])
b = np.broadcast(x, y)
out = np.empty(b.shape)
out.flat = [u+v for (u,v) in b]
out

array([[5., 6., 7.],
       [6., 7., 8.],
       [7., 8., 9.]])

In [74]:
x + y

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [75]:
# 45
# numpy.broadcast_to
# numpy.broadcast_to(array, shape, subok=False)
# Broadcast an array to a new shape.

x = np.array([1, 2, 3])
np.broadcast_to(x, (3, 3))

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [76]:
# 46
# numpy.broadcast_arrays
# numpy.broadcast_arrays(*args, subok=False)
# Broadcast any number of arrays against each other.

x = np.array([[1,2,3]])
y = np.array([[4],[5]])
np.broadcast_arrays(x, y)

[array([[1, 2, 3],
        [1, 2, 3]]), array([[4, 4, 4],
        [5, 5, 5]])]

In [77]:
# 47
# numpy.expand_dims
# numpy.expand_dims(a, axis)
# Expand the shape of an array.

y = np.expand_dims(x, axis=1)
y

array([[[1, 2, 3]]])

In [78]:
# 48
# numpy.squeeze
# numpy.squeeze(a, axis=None)
# Remove single-dimensional entries from the shape of an array.

x = np.array([[[0], [1], [2]]])
print(x.shape)
np.squeeze(x).shape
np.squeeze(x, axis=0).shape

(1, 3, 1)


(3, 1)

#### Changing kind of array

In [79]:
# 49
# numpy.asfarray
# numpy.asfarray(a, dtype=<class 'numpy.float64'>)
# Return an array converted to a float type.

np.asfarray([2, 3])
np.asfarray([2, 3], dtype='float')
np.asfarray([2, 3], dtype='int8')

array([2., 3.])

In [80]:
# 50
# numpy.asscalar
# numpy.asscalar(a)
# Convert an array of size 1 to its scalar equivalent.

np.asscalar(np.array([24]))

24

In [81]:
# 51
# numpy.require
# numpy.require(a, dtype=None, requirements=None)
# Return an ndarray of the provided type that satisfies requirements.

x = np.arange(6).reshape(2,3)
x.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

#### Joining arrays

In [82]:
# 52
# numpy.concatenate
# numpy.concatenate((a1, a2, ...), axis=0, out=None)
# Join a sequence of arrays along an existing axis.

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [83]:
# 53
# numpy.stack
# numpy.stack(arrays, axis=0, out=None)
# Join a sequence of arrays along a new axis.

a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
np.stack((a, b))

array([[1, 2, 3],
       [2, 3, 4]])

In [84]:
# 54
# numpy.column_stack
# numpy.column_stack(tup)
# Stack 1-D arrays as columns into a 2-D array.

a = np.array((1,2,3))
b = np.array((2,3,4))
np.column_stack((a,b))

array([[1, 2],
       [2, 3],
       [3, 4]])

In [85]:
# 55
# numpy.dstack
# numpy.dstack(tup)
# Stack arrays in sequence depth wise (along third axis).

a = np.array((1,2,3))
b = np.array((2,3,4))
np.dstack((a,b))

array([[[1, 2],
        [2, 3],
        [3, 4]]])

In [86]:
# 56
# numpy.hstack
# numpy.hstack(tup)
# Stack arrays in sequence horizontally (column wise).

a = np.array([[1],[2],[3]])
b = np.array([[2],[3],[4]])
np.hstack((a,b))

array([[1, 2],
       [2, 3],
       [3, 4]])

In [87]:
# 57
# numpy.vstack
# numpy.vstack(tup)
# Stack arrays in sequence vertically (row wise).

a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
np.vstack((a,b))

array([[1, 2, 3],
       [2, 3, 4]])

In [88]:
a = np.array([[1], [2], [3]])
b = np.array([[2], [3], [4]])
np.vstack((a,b))

array([[1],
       [2],
       [3],
       [2],
       [3],
       [4]])

In [89]:
# 58
# numpy.block
# numpy.block(arrays)
# Assemble an nd-array from nested lists of blocks.

A = np.eye(2) * 2
B = np.eye(3) * 3
np.block([[A,np.zeros((2, 3))],[np.ones((3, 2)), B]])

array([[2., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [1., 1., 3., 0., 0.],
       [1., 1., 0., 3., 0.],
       [1., 1., 0., 0., 3.]])

#### Splitting arrays

In [90]:
# 59
# numpy.split
# numpy.split(ary, indices_or_sections, axis=0)
# Split an array into multiple sub-arrays as views into ary.

x = np.arange(9.0)
np.split(x, 3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

In [91]:
# 61
# numpy.array_split
# numpy.array_split(ary, indices_or_sections, axis=0)
# Split an array into multiple sub-arrays.

x = np.arange(8.0)
np.array_split(x, 3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7.])]

In [92]:
# 62
# numpy.dsplit
# numpy.dsplit(ary, indices_or_sections)
# Split array into multiple sub-arrays along the 3rd axis (depth).

x = np.arange(16.0).reshape(2, 2, 4)
np.dsplit(x, 2)
np.dsplit(x, np.array([3, 6]))

[array([[[ 0.,  1.,  2.],
         [ 4.,  5.,  6.]],
 
        [[ 8.,  9., 10.],
         [12., 13., 14.]]]), array([[[ 3.],
         [ 7.]],
 
        [[11.],
         [15.]]]), array([], shape=(2, 2, 0), dtype=float64)]

In [93]:
# 63
# numpy.hsplit
# numpy.hsplit(ary, indices_or_sections)
# Split an array into multiple sub-arrays horizontally (column-wise).

x = np.arange(16.0).reshape(4, 4)
np.hsplit(x, 2)
np.hsplit(x, np.array([3, 6]))

[array([[ 0.,  1.,  2.],
        [ 4.,  5.,  6.],
        [ 8.,  9., 10.],
        [12., 13., 14.]]), array([[ 3.],
        [ 7.],
        [11.],
        [15.]]), array([], shape=(4, 0), dtype=float64)]

In [94]:
# 64
# numpy.vsplit
# numpy.vsplit(ary, indices_or_sections)
# Split an array into multiple sub-arrays vertically (row-wise).

x = np.arange(16.0).reshape(4, 4)
np.vsplit(x, 2)
np.vsplit(x, np.array([3, 6]))

[array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]),
 array([[12., 13., 14., 15.]]),
 array([], shape=(0, 4), dtype=float64)]

#### Tiling arrays

In [95]:
# 65
# numpy.tile
# numpy.tile(A, reps)
# Construct an array by repeating A the number of times given by reps.

a = np.array([0, 1, 2])
np.tile(a, 5)

array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2])

In [96]:
# 66
# numpy.repeat
# numpy.repeat(a, repeats, axis=None)
# Repeat elements of an array.

np.repeat(3, 4)

array([3, 3, 3, 3])

In [97]:
x = np.array([[1,2],[3,4]])
np.repeat(x, 2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [98]:
np.repeat(x, 3, axis=1)

array([[1, 1, 1, 2, 2, 2],
       [3, 3, 3, 4, 4, 4]])

In [99]:
np.repeat(x, [1, 2], axis=0)

array([[1, 2],
       [3, 4],
       [3, 4]])

#### Adding and removing elements

In [100]:
# 67
# numpy.delete
# numpy.delete(arr, obj, axis=None)
# Return a new array with sub-arrays along an axis deleted. 
# For a one dimensional array, this returns those entries not returned by arr[obj].

arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(arr)
np.delete(arr, 1, 0)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [101]:
# 68
# numpy.insert
# numpy.insert(arr, obj, values, axis=None)
# Insert values along the given axis before the given indices.

a = np.array([[1, 1], [2, 2], [3, 3]])
print(a)
np.insert(a, 1, 5)

[[1 1]
 [2 2]
 [3 3]]


array([1, 5, 1, 2, 2, 3, 3])

In [102]:
np.insert(a, 1, 5, axis=1)

array([[1, 5, 1],
       [2, 5, 2],
       [3, 5, 3]])

In [103]:
# 69
# numpy.append
# numpy.append(arr, values, axis=None)
# Append values to the end of an array.

np.append([1, 2, 3], [[4, 5, 6], [7, 8, 9]])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [104]:
# 70
# numpy.resize
# numpy.resize(a, new_shape)
# Return a new array with the specified shape.

a=np.array([[0,1],[2,3]])
np.resize(a,(2,3))

array([[0, 1, 2],
       [3, 0, 1]])

In [105]:
# 71
# numpy.trim_zeros
# numpy.trim_zeros(filt, trim='fb')
# Trim the leading and/or trailing zeros from a 1-D array or sequence.

a = np.array((0, 0, 0, 1, 2, 3, 0, 2, 1, 0))
np.trim_zeros(a)

array([1, 2, 3, 0, 2, 1])

In [106]:
# 72
# numpy.unique
# numpy.unique(ar, return_index=False, return_inverse=False, 
# return_counts=False, axis=None)
# Find the unique elements of an array.

np.unique([1, 1, 2, 2, 3, 3])

array([1, 2, 3])

In [107]:
a = np.array([[1, 1], [2, 3]])
np.unique(a)

array([1, 2, 3])

#### Rearranging elements

In [108]:
# 73
# numpy.flip
# numpy.flip(m, axis=None)
# Reverse the order of elements in an array along the given axis.

A = np.arange(8).reshape((2,2,2))
print(A)
np.flip(A, 0)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


array([[[4, 5],
        [6, 7]],

       [[0, 1],
        [2, 3]]])

In [109]:
np.flip(A, 1)

array([[[2, 3],
        [0, 1]],

       [[6, 7],
        [4, 5]]])

In [110]:
np.flip(A)

array([[[7, 6],
        [5, 4]],

       [[3, 2],
        [1, 0]]])

In [111]:
# 74
# numpy.fliplr
# numpy.fliplr(m)
# Flip array in the left/right direction.

A = np.diag([1.,2.,3.])
print(A)
np.fliplr(A)

[[1. 0. 0.]
 [0. 2. 0.]
 [0. 0. 3.]]


array([[0., 0., 1.],
       [0., 2., 0.],
       [3., 0., 0.]])

In [112]:
# 75
# numpy.flipud
# numpy.flipud(m)
# Flip array in the up/down direction.

A = np.diag([1.0, 2, 3])
print(A)
np.flipud(A)

[[1. 0. 0.]
 [0. 2. 0.]
 [0. 0. 3.]]


array([[0., 0., 3.],
       [0., 2., 0.],
       [1., 0., 0.]])

In [113]:
# 76
# numpy.roll
# numpy.roll(a, shift, axis=None)
# Roll array elements along a given axis.

x = np.arange(10)
print(x)
np.roll(x, 2)
np.roll(x, -2)

[0 1 2 3 4 5 6 7 8 9]


array([2, 3, 4, 5, 6, 7, 8, 9, 0, 1])

In [114]:
# 77
# numpy.rot90
# numpy.rot90(m, k=1, axes=(0, 1))
# Rotate an array by 90 degrees in the plane specified by axes.

m = np.array([[1,2],[3,4]], int)
print(m)
np.rot90(m)

[[1 2]
 [3 4]]


array([[2, 4],
       [1, 3]])

## Binary operations

#### Elementwise bit operations

In [115]:
# 78
# numpy.bitwise_and
# numpy.bitwise_and(x1, x2, /, out=None, *, where=True, casting='same_kind', 
# order='K', dtype=None, subok=True[, signature, extobj]) = <ufunc 'bitwise_and'>
# Compute the bit-wise AND of two arrays element-wise.

np.bitwise_and(14, 13)

12

In [116]:
np.binary_repr(12)

'1100'

In [117]:
np.bitwise_and([14,3], 13)

array([12,  1], dtype=int32)

In [118]:
# 79
# numpy.bitwise_or
# numpy.bitwise_or(x1, x2, /, out=None, *, where=True, casting='same_kind', 
# order='K', dtype=None, subok=True[, signature, extobj]) = <ufunc 'bitwise_or'>
# Compute the bit-wise OR of two arrays element-wise.

np.bitwise_or(32, 2)

34

In [119]:
np.bitwise_or([33, 4], 1)

array([33,  5], dtype=int32)

In [120]:
np.bitwise_or([33, 4], [1, 2])

array([33,  6], dtype=int32)

In [121]:
# 80
# numpy.bitwise_xor
# numpy.bitwise_xor(x1, x2, /, out=None, *, where=True, casting='same_kind', 
# order='K', dtype=None, subok=True[, signature, extobj]) = <ufunc 'bitwise_xor'>
# Compute the bit-wise XOR of two arrays element-wise.

np.bitwise_xor(13, 17)
np.binary_repr(28)

'11100'

In [122]:
# 81
# numpy.invert
# numpy.invert(x, /, out=None, *, where=True, casting='same_kind', order='K', 
# dtype=None, subok=True[, signature, extobj]) = <ufunc 'invert'>
# Compute bit-wise inversion, or bit-wise NOT, element-wise.

x = np.invert(np.array(13, dtype=np.uint8))
np.binary_repr(x, width=8)

'11110010'

In [123]:
# 82
# numpy.left_shift
# numpy.left_shift(x1, x2, /, out=None, *, where=True, casting='same_kind', 
# order='K', dtype=None, subok=True[, signature, extobj]) = <ufunc 'left_shift'>
# Shift the bits of an integer to the left.

np.binary_repr(5)

'101'

In [124]:
np.left_shift(5, 2)

20

In [125]:
np.binary_repr(20)

'10100'

In [126]:
# 83
# numpy.right_shift
# numpy.right_shift(x1, x2, /, out=None, *, where=True, casting='same_kind', 
# order='K', dtype=None, subok=True[, signature, extobj]) = <ufunc 'right_shift'>
# Shift the bits of an integer to the right.

np.binary_repr(10)

'1010'

In [127]:
np.right_shift(10, 1)

5

In [128]:
np.binary_repr(5)

'101'

#### Bit packing

In [129]:
# 84
# numpy.packbits
# numpy.packbits(a, axis=None, bitorder='big')
# Packs the elements of a binary-valued array into bits in a uint8 array.

a = np.array([[[1,0,1],[0,1,0]],[[1,1,0],[0,0,1]]])
b = np.packbits(a, axis=-1)
b

array([[[160],
        [ 64]],

       [[192],
        [ 32]]], dtype=uint8)

In [130]:
# 85
# numpy.unpackbits
# numpy.unpackbits(a, axis=None, count=None, bitorder='big')
# Unpacks elements of a uint8 array into a binary-valued output array.

a = np.array([[2], [7], [23]], dtype=np.uint8)
a

array([[ 2],
       [ 7],
       [23]], dtype=uint8)

In [131]:
b = np.unpackbits(a, axis=1)
b

array([[0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 0, 1, 1, 1]], dtype=uint8)

#### Output formatting

In [132]:
# 86
# numpy.binary_repr
# numpy.binary_repr(num, width=None)
# Return the binary representation of the input number as a string.

np.binary_repr(3)

'11'

In [133]:
np.binary_repr(-3)

'-11'

In [134]:
np.binary_repr(3, width=4)

'0011'


2. Crear un ejemplo de cómo guardar y cargar arreglos de un archivo binario `.npy` y `.npz`:

    - [NumPy binary files (NPY, NPZ)](https://numpy.org/devdocs/reference/routines.io.html#numpy-binary-files-npy-npz)
    

#### Ejemplo de Npy

In [135]:
# numpy.save
# numpy.save(file, arr, allow_pickle=True, fix_imports=True)
# Save an array to a binary file in NumPy .npy format.

# Ejemplo para escritura, varios objetos
with open('elmer_lemus.npy', 'wb') as f:
    np.save(f, np.array([1, 8]))
    np.save(f, np.array([3, 3]))

In [136]:
# Ejemplo para lectura
with open('elmer_lemus.npy', 'rb') as f:
    a = np.load(f)
    b = np.load(f)
print(a, b)

[1 8] [3 3]


In [137]:
# numpy.load
# numpy.load(file, mmap_mode=None, allow_pickle=False, 
# fix_imports=True, encoding='ASCII')
# Load arrays or pickled objects from .npy, .npz or pickled files.

x = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])

np.save('elmer_lemus.npy', x)

In [138]:
# Carga de archivos Npy
np.load('elmer_lemus.npy')

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

#### Ejemplo Npz

In [139]:
# Guardar documentos en Npz, como diccionarios

a = [1, 2, 3, 4, 5, 6, 7]
b = [8, 9, 10, 11, 12, 13, 14]

# Guardar
np.savez('elmer_lemus.npz', a = a, b = b, x = x)

In [140]:
# Cargar
z = np.load('elmer_lemus.npz')
z["x"]

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

3. Crear un ejemplo de cómo guardar y cargar arreglos de un archivo de texto `.txt`:

    - [NumPy Text files](https://numpy.org/devdocs/reference/routines.io.html#text-files)    
    

#### Guardar documentos en txt

In [141]:
# Para Guardar
# numpy.savetxt
# numpy.savetxt(fname, X, fmt='%.18e', delimiter=' ', newline='n', header='', 
# footer='', comments='# ', encoding=None)
# Save an array to a text file.

# Genera array para las variables
a = np.arange(1,15,3)
b = np.random.random((5,5))
np.savetxt('elmer_lemus', b, delimiter=',')

#### Cargar  documentos en txt 

In [142]:
# numpy.loadtxt
# numpy.loadtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, 
# converters=None, skiprows=0, usecols=None, unpack=False, ndmin=0, encoding='bytes', max_rows=None)
# Load data from a text file.

# Cargar los valores en txt, de todas las variables
np.loadtxt('elmer_lemus', delimiter=',')

array([[0.50889365, 0.76500891, 0.28625876, 0.87839051, 0.6947297 ],
       [0.5161112 , 0.35381102, 0.08227133, 0.42796017, 0.85738407],
       [0.16952571, 0.89618782, 0.25064868, 0.586112  , 0.03376445],
       [0.88035136, 0.09726895, 0.99777774, 0.44037068, 0.28724092],
       [0.81691323, 0.41296088, 0.22636114, 0.61887147, 0.86334617]])

4. Crear una función llamada `estimacionMCO` que lea un archivo CSV con 7 columnas, que corresponden a las variables $(x_{1i}, \ldots, x_{6i})$ y $y_i$. 
    - La función debe computar matricialmente los parámetros del modelo de regresión lineal: $y = X\beta$. 
    - Estos parámetros deben ser devueltos como un arreglo de NumPy. 

    - Utilice la función de lectura de archivos de NumPy.

In [143]:
# Extrae los datos

def estimacionMCO(datos):
    
    # Utilizamos la función de lectura "np.genfromtxt"
    matrix = np.genfromtxt(datos, delimiter=',', dtype=int, skip_header=1)
    return matrix

In [144]:
# Extrae los datos
data = estimacionMCO("estimacion_mco.csv")

In [145]:
# Todos los datos
data

array([[200, 172,  50, ..., 163, 166, 151],
       [ 18,  67,  23, ..., 135,  46,  87],
       [118,  84,  78, ..., 125, 196,  50],
       ...,
       [127, 195,  86, ..., 124, 122,  55],
       [108, 102,  46, ...,  53,  52,  48],
       [ 82,  43, 198, ..., 198, 125, 197]])

In [146]:
# Variables independientes
x = data[:,:6]
x

array([[200, 172,  50,  81, 163, 166],
       [ 18,  67,  23, 197, 135,  46],
       [118,  84,  78,  99, 125, 196],
       ...,
       [127, 195,  86,  71, 124, 122],
       [108, 102,  46,  24,  53,  52],
       [ 82,  43, 198, 168, 198, 125]])

In [147]:
# Variables dependientes
y = data[:,6:7]
y

array([[151],
       [ 87],
       [ 50],
       [ 69],
       [157],
       [176],
       [163],
       [113],
       [150],
       [152],
       [ 43],
       [155],
       [ 78],
       [ 32],
       [ 11],
       [167],
       [168],
       [105],
       [ 63],
       [117],
       [ 49],
       [ 98],
       [142],
       [ 29],
       [ 58],
       [101],
       [ 59],
       [ 27],
       [186],
       [ 79],
       [168],
       [179],
       [122],
       [ 13],
       [112],
       [ 94],
       [123],
       [ 82],
       [168],
       [ 70],
       [ 22],
       [ 69],
       [176],
       [142],
       [147],
       [ 94],
       [102],
       [ 77],
       [ 83],
       [154],
       [ 96],
       [ 73],
       [118],
       [163],
       [169],
       [140],
       [ 49],
       [164],
       [ 13],
       [ 51],
       [ 73],
       [ 30],
       [ 31],
       [109],
       [132],
       [ 16],
       [ 30],
       [189],
       [ 74],
       [ 93],
       [ 66],
      

In [148]:
# Operación 1
xTransx = x.T@x

# Operación 2
inver = np.linalg.inv(xTransx)

# Operación 3
xTPorY = x.T@y

# Operaci+on final
betas = inver @ xTPorY

# La estimación de los parámetros es:
betas

array([[ 0.26788365],
       [ 0.15318317],
       [ 0.11887418],
       [ 0.15614557],
       [ 0.24163836],
       [-0.00525159]])